import numpy as np
import object


# McDonald's Logo coordinates are generated by Chat GPT 4.o
mcdonalds_logo_vectors = np.array([
    # Left arch (from bottom left to top of the first arch)
    [-2.5, 0], [-2.25, 2.5], [-2, 4], [-1.75, 5], [-1.5, 6],
    [-1.25, 6.5], [-1, 6.75], [-0.5, 6.75], [-0.25, 6.5],
    [0, 6], [0.25, 5], [0.5, 4], [0.75, 2.5], [1, 1],
    # Right arch (from bottom of the first arch to top of the second arch)
    [1, 1], [1.25, 2.5], [1.5, 4], [1.75, 5], [2, 6],
    [2.25, 6.5], [2.5, 6.75], [3, 6.75], [3.25, 6.5],
    [3.5, 6], [3.75, 5], [4, 4], [4.25, 2.5], [4.5, 0]

])
mcdonalds_obj = object.Object(mcdonalds_logo_vectors, "McDonald's Logo", 'gold')

# Nike 'Swoosh' Logo coordinates are obrained imperically by Kira Zholtikova
nike_swoosh_vectors = np.array([
    [1.5, 9], [0.5, 7.75], [0.25, 7], [0, 6], [0.25, 5.5],
    [1, 5.25], [3.75, 6.25], [11, 9.5], [1.75, 6.75], [1.25, 7], [1.5, 9]
])
nike_obj = object.Object(nike_swoosh_vectors, "Nike 'Swoosh' Logo", 'saddlebrown')
